### ISSUE TITLE
Create multistep form for registering to the global training.

### ISSUE THREAD

**Issue by danielpopdan** [danielpopdan/drupal-community-cluj#15]

**Comment by cbianca** [comment]
/global-training/registration

**Comment by danielpopdan** [comment]
1. When accessing as anonymous user the access is denied.

**Comment by danielpopdan** [comment]
1/ Add the form wrapper (http://demo.zymphonies.com/free-theme/d8/businessgroup-zymphonies-theme/ see contact link)
2/ The order for the buttons should be Back => Next / Register
3/ Please convert the gender radio to select list.
