### ISSUE TITLE
Performance issues.

### ISSUE THREAD

**Issue by danielpopdan** [danielpopdan/drupal-community-cluj#166]
1/ Page cache max age less than 5 minutes
With a page cache max age set to less than 5 minutes, the server has to frequently regenerate pages. This can decrease your site's performance.
Increase page cache for 30 minutes.

2/  Database logging module enabled

With the Database logging module enabled, website events and issues are saved to your database, which can negatively impact your database server's performance.

Use the Syslog module instead of the Database logging module to log events and issues. The Syslog module saves website events to your server's syslog (or Windows eventlog).

**Comment by prics** [comment]
Assigned to Anita.
