### ISSUE TITLE
Create form for event scheduler. 

### ISSUE THREAD

**Issue by danielpopdan** [danielpopdan/drupal-community-cluj#20]

**Comment by luci-gutoiu** [comment]
In order to add a new scheduler, acess /add-scheduler.
Make sure you have the 'Add new global training days scheduler.' permission set for your role.

**Comment by danielpopdan** [comment]
1. Remove the title field from the form. The title will be generated: Training Start Date (d/M/Y) - Training End Date (d/M/Y) 
2. Friday and Saturday Scheduler should be wysiwyg
3. Location should include a text field for address.
