### ISSUE TITLE
Breadcrumbs.

### ISSUE THREAD

**Issue by danielpopdan** [danielpopdan/drupal-community-cluj#56]
Homepage: none
Contact: Home(link) >> Contact
Global Training Registration: Home (link) >> Global Training Days (link) >> Registration
Scheduler: Home (link) >> Global Training Days (link) >> Scheduler

**Comment by danielpopdan** [comment]
1. Please remove the link from the last element of the breadcrumb (the current link) and the last > 
2. On http://drupalclujltboipxwtc.devcloud.acquia-sites.com/node/1 the node title is duplicated. 
3. Breadcrumb is missing on this page http://drupalclujltboipxwtc.devcloud.acquia-sites.com/global-training/registration

**Comment by novaFTL** [comment]
1 and 2 fixed in https://github.com/danielpopdan/drupal-community-cluj/pull/104/files
3 no it's not
